// Build step for @agentic/cli — emit a `dist/cli.js` shim that defers to tsx.
//
// Phase 1 ships TypeScript source directly. The `bin` pointer in package.json
// is `./dist/cli.js`; this script writes that file as a small Node entry that
// re-execs itself under tsx so the rest of the CLI (which transitively
// imports `@agentic/contracts` and other workspace packages) can resolve
// relative .ts files without a separate bundle step.
//
// Phase 4 will replace this with an esbuild bundle once the dev/prod surfaces
// diverge enough to need it.

import { mkdir, writeFile, chmod } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const cliRoot = path.resolve(__dirname, "..");
const distDir = path.join(cliRoot, "dist");

const SHIM = `#!/usr/bin/env node
// auto-generated by scripts/build-shim.mjs — do not edit by hand.
import { spawn } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const cliRoot = path.resolve(__dirname, "..");
const entry = path.join(cliRoot, "src", "cli.ts");

// Resolve tsx's ESM loader relative to the CLI package so node can find it
// regardless of where the bin is invoked from.
const require = createRequire(import.meta.url);
const tsxEsm = require.resolve("tsx/esm", { paths: [cliRoot] });

const child = spawn(
  process.execPath,
  ["--import", tsxEsm, entry, ...process.argv.slice(2)],
  { stdio: "inherit" },
);

child.on("exit", (code, signal) => {
  if (signal) process.kill(process.pid, signal);
  else process.exit(code ?? 0);
});
`;

await mkdir(distDir, { recursive: true });
const target = path.join(distDir, "cli.js");
await writeFile(target, SHIM, "utf-8");
await chmod(target, 0o755);
console.log(`agentic cli built: ${target}`);
